// Builds the graded word data from the clean source lists in tool/data/ and
// writes:
//   - lib/src/word_levels_data.dart  (the Dart const map consumed by apps)
//   - data/grade-*.txt               (per-grade word lists, canonical/reusable)
//   - data/word-levels.csv           (flat word,level for any consumer)
//
// Run from the package root:  dart run tool/build.dart
//
// Levels (index): a word is tagged with the EARLIEST it appears at.
//   0 Pre-K        Dolch pre-primer
//   1 Kindergarten Dolch primer + Dolch nouns, Fry 1-50
//   2 Grade 1      Dolch first grade, Fry 51-100
//   3 Grade 2      Dolch second grade, Fry 101-200
//   4 Grade 3      Dolch third grade, Fry 201-300
//   5 Grade 4      Fry 301-500
//   6 Grade 5      Fry 501-1000
//   7 Academic     New Academic Word List headwords (AWL, Coxhead)
//
// Only plain A-Z words of length >= 2 survive. Sources: Fry (public domain),
// Dolch (public domain), AWL (Coxhead — free to use). See README.
import 'dart:convert';
import 'dart:io';

const levelNames = [
  'prek',
  'k',
  '1',
  '2',
  '3',
  '4',
  '5',
  'academic',
];

void main() {
  final dolch = File('tool/data/dolch.js').readAsStringSync();
  final fry = File('tool/data/fry.txt').readAsStringSync();
  final awl = File('tool/data/awl.json').readAsStringSync();

  final level = <String, int>{};
  void tag(String raw, int lvl) {
    final w = raw.trim().toUpperCase();
    if (!RegExp(r'^[A-Z]{2,}$').hasMatch(w)) return;
    final existing = level[w];
    if (existing == null || lvl < existing) level[w] = lvl;
  }

  void tagAll(Iterable<String> words, int lvl) {
    for (final w in words) {
      tag(w, lvl);
    }
  }

  // --- Dolch: explicit grade groups ---------------------------------------
  String dolchGroup(String name) {
    final m = RegExp("let $name\\s*=\\s*'([^']*)'").firstMatch(dolch);
    if (m == null) throw StateError('Dolch group $name not found');
    return m.group(1)!;
  }

  tagAll(dolchGroup('dolchPreK').split(','), 0);
  tagAll(dolchGroup('dolchK').split(','), 1);
  tagAll(dolchGroup('dolchNouns').split(','), 1);
  tagAll(dolchGroup('dolchFirst').split(','), 2);
  tagAll(dolchGroup('dolchSecond').split(','), 3);
  tagAll(dolchGroup('dolchThird').split(','), 4);

  // --- Fry: 4 columns, column-major frequency order (ranks 1..1000) -------
  final fryLines = fry
      .split('\n')
      .map((l) => l.trimRight())
      .where((l) => l.isNotEmpty)
      .toList()
    ..removeAt(0); // header "List 1 .. List 4"
  final ranked = <String>[]; // index 0 == Fry rank 1
  for (var col = 0; col < 4; col++) {
    for (final line in fryLines) {
      final cells = line.split('\t');
      if (col < cells.length && cells[col].trim().isNotEmpty) {
        ranked.add(cells[col].trim());
      }
    }
  }
  int fryLevel(int rank) {
    if (rank <= 50) return 1;
    if (rank <= 100) return 2;
    if (rank <= 200) return 3;
    if (rank <= 300) return 4;
    if (rank <= 500) return 5;
    return 6;
  }

  for (var i = 0; i < ranked.length; i++) {
    tag(ranked[i], fryLevel(i + 1));
  }

  // --- AWL: headwords only (drop inflected/derived subwords) ---------------
  final awlData = jsonDecode(awl) as Map<String, dynamic>;
  for (final sublist in awlData.values) {
    for (final entry in (sublist as Map<String, dynamic>).entries) {
      tag(entry.key, 7);
    }
  }

  // --- Emit -----------------------------------------------------------------
  final words = level.keys.toList()..sort();
  final counts = List.filled(levelNames.length, 0);
  for (final w in words) {
    counts[level[w]!]++;
  }

  // Per-grade text files.
  for (var lvl = 0; lvl < levelNames.length; lvl++) {
    final list = [
      for (final w in words)
        if (level[w] == lvl) w
    ];
    File('data/grade-${levelNames[lvl]}.txt')
        .writeAsStringSync('${list.join('\n')}\n');
  }

  // Flat CSV.
  final csv = StringBuffer('word,level_index,level\n');
  for (final w in words) {
    csv.writeln('$w,${level[w]},${levelNames[level[w]!]}');
  }
  File('data/word-levels.csv').writeAsStringSync(csv.toString());

  // Dart const map.
  final dart = StringBuffer()
    ..writeln('// GENERATED by tool/build.dart — do not edit.')
    ..writeln('//')
    ..writeln('// Word -> earliest level index (0=Pre-K .. 7=Academic).')
    ..writeln('// Per-level counts: ${counts.join(', ')} (total ${words.length}).')
    ..writeln('library;')
    ..writeln()
    ..writeln('const Map<String, int> kWordLevelIndex = {');
  for (final w in words) {
    dart.writeln("  '$w': ${level[w]},");
  }
  dart.writeln('};');
  File('lib/src/word_levels_data.dart').writeAsStringSync(dart.toString());

  stdout.writeln('built ${words.length} words; per-level ${counts.join(', ')}');
}
