// Builds the graded word data from the open source lists in tool/data/ and writes:
//   - lib/src/word_levels_data.dart  (the Dart const map consumed by apps)
//   - data/grade-*.txt               (per-grade word lists, canonical/reusable)
//   - data/word-levels.csv           (flat word,level for any consumer)
//
// Run from the package root:  dart run tool/build.dart
//
// A word takes the EARLIEST (lowest) level it appears at. Levels (index):
//   0  Pre-K        Dolch pre-primer
//   1  Kindergarten Dolch primer + Dolch nouns, Fry 1-50
//   2  Grade 1      Dolch first grade, Fry 51-100
//   3  Grade 2      Dolch second grade, Fry 101-200
//   4  Grade 3      Dolch third grade, Fry 201-300
//   5  Grade 4      Fry 301-500
//   6  Grade 5      Fry 501-1000
//   7  Grade 6      NGSL frequency rank, 1st third
//   8  Grade 7      NGSL 2nd third
//   9  Grade 8      NGSL 3rd third
//   10 Grade 9      NAWL frequency rank, 1st quarter
//   11 Grade 10     NAWL 2nd quarter
//   12 Grade 11     NAWL 3rd quarter
//   13 Grade 12     NAWL 4th quarter
//
// Sources: Fry (public domain), Dolch (public domain), NGSL & NAWL
// (CC BY-SA 4.0). Only plain A-Z words of length >= 2 survive. See README.
import 'dart:io';

const levelNames = [
  'prek', 'k', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
];

void main() {
  final dolch = File('tool/data/dolch.js').readAsStringSync();
  final fry = File('tool/data/fry.txt').readAsStringSync();
  final ngslNawl = File('tool/data/ngsl_nawl.csv').readAsLinesSync();

  final level = <String, int>{};
  void tag(String raw, int lvl) {
    final w = raw.trim().toUpperCase();
    if (!RegExp(r'^[A-Z]{2,}$').hasMatch(w)) return;
    final existing = level[w];
    if (existing == null || lvl < existing) level[w] = lvl;
  }

  void tagAll(Iterable<String> words, int lvl) {
    for (final w in words) {
      tag(w, lvl);
    }
  }

  // --- Dolch: explicit grade groups (public domain) -----------------------
  String dolchGroup(String name) {
    final m = RegExp("let $name\\s*=\\s*'([^']*)'").firstMatch(dolch);
    if (m == null) throw StateError('Dolch group $name not found');
    return m.group(1)!;
  }

  tagAll(dolchGroup('dolchPreK').split(','), 0);
  tagAll(dolchGroup('dolchK').split(','), 1);
  tagAll(dolchGroup('dolchNouns').split(','), 1);
  tagAll(dolchGroup('dolchFirst').split(','), 2);
  tagAll(dolchGroup('dolchSecond').split(','), 3);
  tagAll(dolchGroup('dolchThird').split(','), 4);

  // --- Fry: 4 columns, column-major frequency order (ranks 1..1000) -------
  final fryLines = fry
      .split('\n')
      .map((l) => l.trimRight())
      .where((l) => l.isNotEmpty)
      .toList()
    ..removeAt(0); // header "List 1 .. List 4"
  final ranked = <String>[];
  for (var col = 0; col < 4; col++) {
    for (final line in fryLines) {
      final cells = line.split('\t');
      if (col < cells.length && cells[col].trim().isNotEmpty) {
        ranked.add(cells[col].trim());
      }
    }
  }
  int fryLevel(int rank) {
    if (rank <= 50) return 1;
    if (rank <= 100) return 2;
    if (rank <= 200) return 3;
    if (rank <= 300) return 4;
    if (rank <= 500) return 5;
    return 6;
  }

  for (var i = 0; i < ranked.length; i++) {
    tag(ranked[i], fryLevel(i + 1));
  }

  // --- NGSL (-> G6-8) and NAWL (-> G9-12), split by frequency rank --------
  final ngsl = <(String, int)>[]; // (lemma, rank)
  final nawl = <(String, int)>[];
  for (final line in ngslNawl.skip(1)) {
    final c = line.split(',');
    if (c.length < 3) continue;
    final lemma = c[0];
    final rank = int.tryParse(c[2]);
    if (rank == null) continue;
    if (c[1] == 'NGSL') {
      ngsl.add((lemma, rank));
    } else if (c[1] == 'NAWL') {
      nawl.add((lemma, rank));
    }
  }
  ngsl.sort((a, b) => a.$2.compareTo(b.$2));
  nawl.sort((a, b) => a.$2.compareTo(b.$2));

  // Split a rank-ordered list into [buckets] even bands starting at [baseLevel].
  void tagBands(List<(String, int)> list, int buckets, int baseLevel) {
    for (var i = 0; i < list.length; i++) {
      final bucket = (i * buckets) ~/ list.length;
      tag(list[i].$1, baseLevel + bucket);
    }
  }

  tagBands(ngsl, 3, 7); // G6, G7, G8
  tagBands(nawl, 4, 10); // G9, G10, G11, G12

  // --- Emit -----------------------------------------------------------------
  final words = level.keys.toList()..sort();
  final counts = List.filled(levelNames.length, 0);
  for (final w in words) {
    counts[level[w]!]++;
  }

  for (var lvl = 0; lvl < levelNames.length; lvl++) {
    final list = [
      for (final w in words)
        if (level[w] == lvl) w
    ];
    File('data/grade-${levelNames[lvl]}.txt')
        .writeAsStringSync('${list.join('\n')}\n');
  }

  final csv = StringBuffer('word,level_index,level\n');
  for (final w in words) {
    csv.writeln('$w,${level[w]},${levelNames[level[w]!]}');
  }
  File('data/word-levels.csv').writeAsStringSync(csv.toString());

  final dart = StringBuffer()
    ..writeln('// GENERATED by tool/build.dart — do not edit.')
    ..writeln('//')
    ..writeln('// Word -> earliest level index (0=Pre-K .. 13=Grade 12).')
    ..writeln('// Per-level counts: ${counts.join(', ')} (total ${words.length}).')
    ..writeln('library;')
    ..writeln()
    ..writeln('const Map<String, int> kWordLevelIndex = {');
  for (final w in words) {
    dart.writeln("  '$w': ${level[w]},");
  }
  dart.writeln('};');
  File('lib/src/word_levels_data.dart').writeAsStringSync(dart.toString());

  stdout.writeln('built ${words.length} words; per-level ${counts.join(', ')}');
}
